FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base

ENV ASPNETCORE_HTTP_PORTS=
ENV ASPNETCORE_HTTPS_PORTS=8443
ENV ASPNETCORE_Kestrel__Certificates__Default__Path=/https/server.crt
ENV ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/server.key

USER root

RUN apt-get update && \
    apt-get upgrade -y --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /https /data /app/obj /app/wwwroot2 && \
    chown -R $APP_UID:$APP_UID /https /data /app

RUN mkdir -p /https

WORKDIR /https
COPY --chown=$APP_UID:$APP_UID server.crt .
COPY --chown=$APP_UID:$APP_UID server.key .
RUN chmod 644 server.crt && chmod 600 server.key

WORKDIR /app

USER $APP_UID

EXPOSE $ASPNETCORE_HTTPS_PORTS