name: Build for 10.0

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - main

env:
  VERSION: '10.0'
  DH_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-runtime

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build & Push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile.${{env.VERSION}}
          push: false
          platforms: |
            linux/amd64
          tags: |
            ${{ env.DH_IMAGE_NAME }}:${{ env.VERSION }}
