name: Build for 8.0

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile-8.0'

env:
  VERSION: "18.0"
  DH_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-runtime

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          platforms: |
            linux/amd64
          tags: |
            ${{ env.DH_IMAGE_NAME }}:${{ env.VERSION }}
